# Generated by Django 3.0.5 on 2020-12-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fname',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='student',
            name='mname',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
